StartupEvents.registry("item", e => {
    e.create("unfinished_slimeball","create:sequenced_assembly")
    e.create("incomplete_logic_processor","create:sequenced_assembly")
    e.create("incomplete_calculation_processor","create:sequenced_assembly")
    e.create("incomplete_engineering_processor","create:sequenced_assembly")
    e.create("incomplete_printed_silicon","create:sequenced_assembly")
    e.create("incomplete_printed_logic_processor").displayName("Incomplete Printed Logic Circuit")
    e.create("incomplete_printed_calculation_processor").displayName("Incomplete Printed Calculation Circuit")
    e.create("incomplete_printed_engineering_processor").displayName("Incomplete Printed Calculation Circuit")
    e.create("incomplete_silicon_press").displayName("Incomplete Silicon Press")
    e.create("incomplete_logic_processor_press").displayName("Incomplete Logic Processor Press")
    e.create("incomplete_calculation_processor_press").displayName("Incomplete Calculation Processor Press")
    e.create("incomplete_engineering_processor_press").displayName("Incomplete Engineering Processor Press")
})